---
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.freshrss.loadbalancer.server.port=80
      - traefik.http.routers.freshrss.entrypoints=web
      - traefik.http.routers.freshrss.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.freshrss-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.freshrss.middlewares=freshrss-https-redirect
      - traefik.http.routers.freshrss-secure.entrypoints=websecure
      - traefik.http.routers.freshrss-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.freshrss-secure.tls=true
      - traefik.http.routers.freshrss-secure.tls.certresolver=letsencrypt
    networks:
      - proxy

networks:
  proxy:
    external: true
